# fly.toml file generated for grafana-agent-dev on 2022-04-06T13:07:15-07:00

app = "grafana-agent-dev"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
# We don't have any inbound traffic so we don't need any services
